services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_POSTGRESQL_URL: jdbc:postgresql://db:5432/hackathon
      SPRING_DATASOURCE_POSTGRESQL_USERNAME: postgres
      SPRING_DATASOURCE_POSTGRESQL_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hackathon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5